version: '3.9'

services:
  web:
    build:
      x-bake:
        platforms:
          - linux/amd64
      context: ../
      dockerfile: conf/Dockerfile
    restart: on-failure
    environment:
      COMPOSE_FILE: ./conf/docker-compose.yml
      DEVELOPMENT: 'true'
      DEBUG: 'true'
      TEST: 'true'
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - "4200:4200"